/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Vehiculo;

import Objetos.Vehiculo;
import codigo.CRUD_Codigo_Modificar;
import codigo.Cargar_Foto;
import codigo.Cargar_Info_Cod;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class Modificar_Vehiculo extends javax.swing.JDialog {

    /**
     * Creates new form Modificar_Vehiculo
     */
    FileInputStream fis;
    int longitudBytes;
    Vehiculo vehiculo;
    public Modificar_Vehiculo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Cargar_Combos();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca_letras = new javax.swing.JTextField();
        txtPlaca_num = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcbMarcas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbEstilos = new javax.swing.JComboBox<>();
        jcbModelos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jrbManual = new javax.swing.JRadioButton();
        jrbAutomatico = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        jrbDisponible = new javax.swing.JRadioButton();
        jrbOcupado = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Placa:");

        jLabel2.setText("-");

        txtPlaca_letras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlaca_letrasKeyTyped(evt);
            }
        });

        txtPlaca_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlaca_numKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca:");

        jLabel4.setText("Estilo:");

        jLabel5.setText("Modelo:");

        buttonGroup1.add(jrbManual);
        jrbManual.setSelected(true);
        jrbManual.setText("Manual");

        buttonGroup1.add(jrbAutomatico);
        jrbAutomatico.setText("Automatico");

        jLabel6.setText("Año:");

        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        jLabel7.setText("Precio:");

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        lblFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFoto.setText("Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbDisponible);
        jrbDisponible.setSelected(true);
        jrbDisponible.setText("Disponible");

        buttonGroup2.add(jrbOcupado);
        jrbOcupado.setText("Ocupado");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca_letras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca_num, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(txtYear, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jcbMarcas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbModelos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbEstilos, 0, 120, Short.MAX_VALUE))
                                .addGap(132, 132, 132)
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbAutomatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbDisponible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbOcupado))
                            .addComponent(btnModificar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca_letras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbModelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbManual)
                    .addComponent(jrbAutomatico)
                    .addComponent(btnFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDisponible)
                    .addComponent(jrbOcupado))
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlaca_letrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlaca_letrasKeyTyped
        char c = evt.getKeyChar();
        String placa = txtPlaca_letras.getText();
        if (placa.length() <= 2) {
            if (!Character.isLetter(c)) {
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtPlaca_letrasKeyTyped

    private void txtPlaca_numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlaca_numKeyTyped
        char c = evt.getKeyChar();
        String placa = txtPlaca_num.getText();
        if (placa.length() <= 2) {
            if (c < '0' || c > '9' && c != '\b') {
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtPlaca_numKeyTyped

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' && c != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9' && c != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Cargar_Info_Cod cic = new Cargar_Info_Cod();
        vehiculo = cic.Buscar_Vehiculo(txtPlaca_letras.getText() + '-' + txtPlaca_num.getText());
        if (vehiculo != null) {
            Cargar_Vehiculo();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Cargar_Info_Cod cic = new Cargar_Info_Cod();
        int marca = cic.Buscar_Id_Cod("marca",(String)jcbMarcas.getSelectedItem());
        int modelo = cic.Buscar_Id_Cod("modelo",(String)jcbModelos.getSelectedItem());
        int estilo = cic.Buscar_Id_Cod("estilo",(String)jcbEstilos.getSelectedItem());
        vehiculo.setMarca(marca);
        vehiculo.setModelo(modelo);
        vehiculo.setEstilo(estilo);
        vehiculo.setPrecio_dia(Integer.parseInt(txtPrecio.getText()));
        vehiculo.setFabricacion(Integer.parseInt(txtYear.getText()));
        if(jrbAutomatico.isSelected()){
            vehiculo.setTransmision(true);
        }else{
            vehiculo.setTransmision(false);
        }
        if(jrbDisponible.isSelected()){
            vehiculo.setEstado(true);
        }else{
            vehiculo.setEstado(false);
        }
        if(longitudBytes > 0 && fis != null){
            vehiculo.setBytes(longitudBytes);
            vehiculo.setFis(fis);
            CRUD_Codigo_Modificar crud_cm = new CRUD_Codigo_Modificar();
            boolean modificado = crud_cm.Modificar_Vehiculo_Foto_Mod(vehiculo);
            if(modificado){
                JOptionPane.showMessageDialog(null, "Vehiculo modificado");
            }else{
                JOptionPane.showMessageDialog(null, "no se puedo modificar el vehiculo");
            }
        }else{
            CRUD_Codigo_Modificar crud_cm = new CRUD_Codigo_Modificar();
            boolean modificado = crud_cm.Modificar_Vehiculo_Sin_Foto_Mod(vehiculo);
            if(modificado){
                JOptionPane.showMessageDialog(null, "Vehiculo modificado");
            }else{
                JOptionPane.showMessageDialog(null, "no se puedo modificar el vehiculo");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        Cargar_Foto cf = new Cargar_Foto();
        Object[] info_foto = cf.Cargar_foto(lblFoto);
        fis = (FileInputStream) info_foto[0];
        longitudBytes = (int) info_foto[1];
    }//GEN-LAST:event_btnFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar_Vehiculo dialog = new Modificar_Vehiculo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbEstilos;
    private javax.swing.JComboBox<String> jcbMarcas;
    private javax.swing.JComboBox<String> jcbModelos;
    private javax.swing.JRadioButton jrbAutomatico;
    private javax.swing.JRadioButton jrbDisponible;
    private javax.swing.JRadioButton jrbManual;
    private javax.swing.JRadioButton jrbOcupado;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtPlaca_letras;
    private javax.swing.JTextField txtPlaca_num;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void Cargar_Combos() {
        Cargar_Info_Cod cic = new Cargar_Info_Cod();
        cic.Cargar_Combos(jcbMarcas, jcbModelos, jcbEstilos);
        jcbMarcas.repaint();
        jcbEstilos.repaint();
        jcbModelos.repaint();
    }

    private void Cargar_Vehiculo() {
        Cargar_Info_Cod cic = new Cargar_Info_Cod();
        
        String marca = cic.nombre_marca_modelo_estilo(vehiculo.getMarca(),"marca");
        String modelo = cic.nombre_marca_modelo_estilo(vehiculo.getModelo(),"modelo");
        String estilo = cic.nombre_marca_modelo_estilo(vehiculo.getEstilo(),"estilo");
        try {
            ImageIcon carg_fot;
            jcbMarcas.setSelectedItem(marca);
            jcbModelos.setSelectedItem(modelo);
            jcbEstilos.setSelectedItem(estilo);
            txtPrecio.setText(String.valueOf(vehiculo.getPrecio_dia()));
            txtYear.setText(String.valueOf(vehiculo.getFabricacion()));
            if (vehiculo.getTransmision()) {
                jrbAutomatico.setSelected(true);
            } else {
                jrbManual.setSelected(true);
            }
            if (vehiculo.getEstado()) {
                jrbDisponible.setSelected(true);
            } else {
                jrbOcupado.setSelected(true);
            }
            BufferedImage bi = ImageIO.read(vehiculo.getFoto());
            carg_fot = new ImageIcon(bi);
            Image img = carg_fot.getImage();
            Image newimg = img.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon newicon = new ImageIcon(newimg);
            lblFoto.setIcon(newicon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
